# Generated by Django 4.0.1 on 2022-02-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='tag',
            field=models.CharField(choices=[('Dogs', 'Dogs')], default='Cats', max_length=200),
            preserve_default=False,
        ),
    ]
