# Generated by Django 4.0.1 on 2022-02-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsstory_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image',
            field=models.URLField(default='https://picsum.photos/600'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
