# Generated by Django 4.0.1 on 2022-02-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_newsstory_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='tag',
            field=models.CharField(choices=[('Basic features', 'Basic features'), ('Additional features', 'Additional features'), ('Cool stuff', 'Cool stuff'), ('News', 'News')], default='News', max_length=200),
        ),
    ]
