# Generated by Django 4.0.1 on 2022-02-19 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_tag_remove_newsstory_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='news.tag'),
        ),
    ]
